### ISSUE TITLE
Silkscreen superposed to pads TO-252-2Lead

### ISSUE THREAD

**Issue by diggit** [KiCad/TO_SOT_Packages_SMD.pretty#31]
FP: TO-252-2Lead has silkscreen over lead pads. KLC not compliant FP at all.

*Sorry guys, I don't have time to work on it ATM.*

**Comment by evanshultz** [comment]
I don't see this now. Maybe the footprint was already updated or I'm not seeing the issue?
![image](https://cloud.githubusercontent.com/assets/1936989/24662793/02af99de-190b-11e7-92fd-473b2787e452.png)

@diggit If this isn't a problem now, please close this issue.

**Comment by evanshultz** [comment]
@jkriege2 I don't see any superimposed silk. But maybe the concern is that silk is too close to pad 2? If this is fine now, can this issue be closed?

**Comment by evanshultz** [comment]
Closing this case since the footprints apparently have been updated already and there isn't superimposed silk on the TO252 footprints in the current library.
