### ISSUE TITLE
SOT-343 / SC-70-4 footprint

### ISSUE THREAD

**Issue by evanshultz** [KiCad/TO_SOT_Packages_SMD.pretty#36]
While looking at the ADCMP35x datasheet, I see it has 3 small pins and one big pin. Our SOT-343/SC-70-4 footprint has 4 small pins.

Looking for "sot-343" and "sc-70-4" I found loads of examples where there is one big pin. In fact, I'm struggling to find any with all equal pins. Here are examples:
http://www.analog.com/media/en/package-pcb-resources/package/pkg_pdf/sc70ks/ks_4.pdf
https://datasheets.maximintegrated.com/en/ds/MAX6711-MAX6713Z.pdf
http://www.nxp.com/assets/documents/data/en/package-information/98ARH98309A.pdf
https://www.centralsemi.com/PDFs/case/SOT-343PD.PDF
http://www.infineon.com/dgdl/SOT343-Package_Overview.pdf?fileId=5546d462580663ef015806a5338d04ef
http://www.alliedelec.com/m/d/86764bfc69af7e3c99e823193fd29076.pdf

All of them are compatible if the big pin is rotated to the lower right, though pin number varies.

Can anyone find an example of this package with 4 small pins? If so, we need to add footprints with one big pin, and then what should the naming convention be?

If not, should we change our existing footprints to have one big pin? According to KLC, the symbol should fit the footprint pin numbering so I think we start with pin 1 in the lower left and the big pin is pin 2.

**Comment by jkriege2** [comment]
Would the SOT-143/SOT-143R in the lib possibly match you footprints? Then that would maybe be a naming issue???

Didn't we already discuss this in length here: https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/26#issuecomment-271551286

**Comment by evanshultz** [comment]
Thanks for commenting, Jan.

SOT-143 is a different body size.

I found that discussion to which you linked, but this issue was to clarify two points I didn't see covered or that had reached the end of the discussion there:
1. Are there any SC-70-4 parts with all small pins? A quick look today and I didn't see any. Pinouts varied but all I saw had the big pad in the lower left as shown in the links above. Therefore, I'm not sure whether the existing footprints are OK or should change. Since the big pin will key the part, perhaps no vendor uses a package with 4 equal pins and only relies on part marking for polarity.
1. What should the naming convention be? Personally, I don't like `AllPinsSmall` or `LargePad2` as a footprint suffix. I don't, however, have a good proposal right now.

So with a decision on those issues I'll happily update or add footprints as needed.

**Comment by jkriege2** [comment]
@SchrodingersGat Do you have any comments/insight on this?

**Comment by jkriege2** [comment]
I checke Target3001! (older version). they have these:
![2017-03-15 06_57_07-gehause auswahlen](https://cloud.githubusercontent.com/assets/11967523/23935511/aba4dd98-094c-11e7-8915-e8da7a024c76.png)
![2017-03-15 06_57_40-gehause auswahlen](https://cloud.githubusercontent.com/assets/11967523/23935519/b5ecd904-094c-11e7-993d-9ea705e61ef1.png)
![2017-03-15 06_58_48-gehause auswahlen](https://cloud.githubusercontent.com/assets/11967523/23935571/dd010696-094c-11e7-8fe0-d1b64bdb406e.png)

... and no SC-70

**Comment by evanshultz** [comment]
It seems like this package is rather varied and confusing.  I'm not sure what would be an obvious name for it to a typical CAD user.

I found that SC-82 appears to be a standard name for SOT-343 as well. And that lead me to finding a number of links using "SC-82", some with 4 equal leads and some with one big pin:
http://www.leadtrend.com.tw/archive/doc/dimensions/SC82-4.pdf
http://www.njr.com/semicon/package/SC-82AB_E.html
http://www.richtek.com/assets/product_file/RT9013A/DS9013A-02.pdf
https://www.onsemi.com/pub/Collateral/NCP698-D.PDF
http://www.gmt.com.tw/product/datasheet/EDS-678.pdf
http://rohmfs.rohm.com/en/products/databook/package/spec/discrete/diodepkg.pdf
http://www.skywilltek.com/WebEditor/UploadFile/2010426112624150.pdf

The above is a mess. It seems different vendors use the same name for different packages. I'll hunt around the JEDEC website and similar places to see if there is a standard which is being corrupted by the above and gives us a clear path for package naming here.

**Comment by SchrodingersGat** [comment]
I think we should have an SC-70-4 which has all normal sized pins. Then two versions of SOT-343 with large pins (pin 1 or pin 2).

I've found at least one reference to a standard SC-70-4 http://www.richtek.com/~/media/Richtek/Design%2520Support/File/Footprints-100330.pdf

However I haven't found a good guide on how to name SOT-343 pin variants.  If we cannot find a good source I would suggest SOT-343 is big pin 1, SOT-343R is pin 2

**Comment by evanshultz** [comment]
I found some SC-70-4 with equal pins too. Naming is what escapes me too. We can choose any name we like, but haven't yet found any industry standard that would tell us how best to name them so KiCad users will find it obvious which package they want.

It appears JEDEC info requires payment, but one or more of the following may cover our packages:
- MO-193
- MO-203
- MO-223
- TO-253
- TO-261

JEITA (they publish SC-* specs) also has info that may be applicable. EIAJ ED-7500A has only a single entry for SC-70 with just 3 pins. Maybe variants with more than 3 pins are vendor-derived but not from an actual published spec?? It shows SC-82 versions with a thicker pin 1 pin at the lower right (or upper left); 0.2/0.3mm and 0.3/0.4mm variants are called SC-82AA and SC-82AB. (Regular SC-82 has all four pins 0.4mm wide.)

**Comment by SchrodingersGat** [comment]
I have found the SC82 variants here, as well as a SC70-3 (no -4)

* http://www.richtek.com/assets/product_file/RT9818/DS9818-10.pdf

Perhaps  we need the following:

* SC-70-3 (perhaps just called SC-70)?
* SC-70-5
* SC-82
* SC-82AA
* SC-82AB

**Comment by evanshultz** [comment]
We already have 3 and 5 pins, and those are fine to my knowledge.

The 4 pin packages are where I think we're not covered. SOT-343 and SC-70-4 are identical package sizes of 2x1.25mm (like SOT-323 and SC-70), but there are a number of different pinouts. We only need two device orientations, with the big pin on the lower left and lower right. (Having the reversed pinout is an annoyance but KLC says not to do that since the footprints shouldn't be duplicated by the symbols should fit an existing footprint if the components are mechanically identical.) This is all clear to me.

What to name the missing packages is the only topic I see that's open. From the JEITA info I wrote above, the 4-lead versions are called SC-82 but I see some vendors call them SC-70. I haven't yet found any SOT-343 that have one big pin.

We have `SOT-343_SC-70-4` currently. We could add the missing two parts (like SC-70-4 but with one big pin) and name them `SC-82AA` and `SC-82AB`, but that leaves off the SC-70 part which would be helpful to users. Perhaps we go with `SC-82AA_SC-70-4` and `SC-82AB_SC-70-4`? That way we put the clearly distinguishing package name first but also include the SC-70 which users may find helpful? In the footprint browser, if they're looking for or being filtered on SC-70 parts, there will be only a few options and it should then be pretty easy to find the one they're looking for. Sound OK?

**Comment by SchrodingersGat** [comment]
That sounds ok to me

**Comment by evanshultz** [comment]
New footprints merged. Closing...
