### ISSUE TITLE
Naming of cut lead versions

### ISSUE THREAD

**Issue by ghost** [KiCad/TO_SOT_Packages_SMD.pretty#46]
How best to name footprints for these two variants of the TO-263 (DDPAK) package?

![image](https://cloud.githubusercontent.com/assets/7076027/25349691/a80b31d0-291a-11e7-89fa-3950292d9d15.png) ![image](https://cloud.githubusercontent.com/assets/7076027/25349831/131377b2-291b-11e7-84aa-d66178f90740.png)

The first is called (by some vendors at least) the TO-263-3L.  The KiCad footprint is `TO-263-3Lead_TabPin4`.

The second, with the centre pin cut short, is the TO-263AA or TO-263AB, also known as SOT-404.  The KiCad footprint is `SOT-404`.

Could the librarians please give me some guidance: 
 - Is there a preference for TO vs SOT where there are equivalent packages?
 - For the cut lead part, if one was going to base the footprint name on the TO designation, should it be `TO-263-3Lead_TabPin4_CutLead`?

Thanks

PS Reason for asking is that I would like to fill some of the gaps in the range of D*PAK footprints and models in the library.

**Comment by jkriege2** [comment]
Hmmm ... for SOT/TO-difference you could also think of adding both names to the name (see e.g. the IPAK in the THT-TO_SOT-lib, or the `SOT-323_SC-70`+variants in this lib). For the two you give above I would propose this:
- `TO-263-3Lead_TabPin4` For the version with 3 pins and the tab as pin 4
- `TO-263-3Lead_TabPin2` For a version with 3 leads and tab=pin2
- `TO-263-2Lead_TabPin3` for the cut-lead version with tab pin 3, or simply `TO-263-2Lead` (cf. `TO-252-2Lead`)
- ...

This TO-SOT-thing is not really solved I think ... you can always also add the different names to the description+tags fields, then one can at least search for them ...

I would vote against `TO-263-3Lead_TabPin4_CutLead` as the cut-pin should usually not be connected!

@SchrodingersGat @pointhi @evanshultz Any ideas on that?

Best,
JAN

**Comment by ghost** [comment]
That makes sense @jkriege2 

I'll follow your suggestions in the first two bullet points.  For the third bullet, I'll take the option `TO-263-2Lead`.  The 252 version has the pin / tab numbering I would expect, so it should work OK for the other packages and numbers of pins.

![image](https://cloud.githubusercontent.com/assets/7076027/25352199/15e22f08-2923-11e7-8638-c18ed3b91e95.png)

**Comment by evanshultz** [comment]
Agreed. Let's make the footprint names succinct and the versions with the middle lead cut really do only have 2 leads (the other connection is a tab, not a lead).

I don't have a JEDEC subscription, but it appears MO-169 or TO-263 are both somehow a descriptions of this package style. Maybe someone has access to those documents?

Can you please put "DDPAK" and "D2PAK" (along with other relevant package names) in the description so either way users will find this footprint? I'm good with leaving this out of the file name as long as it's in the description (`DDPAK_TO-263_3Lead...` is just too darn long!).

SOT-404 is, I believe, Philips/NXP/Nexperia unique name for this package and not an industry name. (Why do they create their own names??) I think KiCad will conform better to standard conventions if SOT-404 and other uniquely-named but exactly-compatible packages aren't used. In other words, I support re-naming `SOT-404` to an industry-standard name. See https://github.com/KiCad/Diodes_SMD.pretty/issues/37 where this exact issue was discussed.

**Comment by ghost** [comment]
>Can you please put "DDPAK" and "D2PAK" (along with other relevant package names) in the description so either way users will find this footprint? 

Will do.

**Comment by ghost** [comment]
Superseded by PR: https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/47
