### ISSUE TITLE
SOT-669: correct footprint centre for "extended" footprints?

### ISSUE THREAD

**Issue by ghost** [KiCad/TO_SOT_Packages_SMD.pretty#51]
I am making a 3D model for the SOT-669 package.  There are three footprints already in the library that will use it:

```
SOT-669_LFPAK.kicad_mod
SOT-669_LFPAK_ThermalVias-1.kicad_mod
SOT-669_LFPAK_ThermalVias-2.kicad_mod
```

The last two footprints have an extended copper region to the right of the device to assist with cooling ...

![image](https://cloud.githubusercontent.com/assets/7076027/26069189/ee3df77c-3997-11e7-9256-df0868a403f4.png)

Regarding KLC rule 8.2, should the extended footprints be moved so that they align with the model (in which case, they will give an 8.2 error) or should the model be given a non-zero offset in the footprint file to align it with the footprints?

Thanks

**Comment by SchrodingersGat** [comment]
The 'origin' of the footprint should be the same in either case, independent of how much copper you place around it. The 3D origin should also be the same for each footprint.

This will mean that 8.2 may fail for the extended footprint.

**Comment by ghost** [comment]
Thanks @SchrodingersGat that's the answer I was hoping for :smile:
