### ISSUE TITLE
Missing hyphen in SOT89-5_Housing breaks footprint filters

### ISSUE THREAD

**Issue by MatthewStephenson** [KiCad/TO_SOT_Packages_SMD.pretty#61]
I think SOT89-5_Housing should be SOT-89-5 (hyphen added, "Housing" removed) to fit with the names of all the other SOT packages in this library.

I came across this issue because the MCP1703A-3302/MB symbol, which is a 3-pin part, has a footprint filter of "SOT89*" (without the hyphen) which makes it match the SOT89-5_Housing footprint, but not the correct SOT-89-3 footprint. (Its footprint field is also wrong, pointing to a nonexistent SOT89-3_Housing footprint)

I can submit a PR to change this footprint's name, but I'm new to this so I don't know what other footprint associations/filters this might break, or whether this is the correct way to handle it.

So, advice sought on how best to fix this!

**Comment by jkriege2** [comment]
hi!

I took the liberty to fix this problem:
- https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/62
- https://github.com/KiCad/kicad-library/pull/1648

@evanshultz @SchrodingersGat Could one of you have a quick look at my PRs?

Thanks,
JAN

**Comment by SchrodingersGat** [comment]
Merged

**Comment by jkriege2** [comment]
fixed!
