### ISSUE TITLE
Missing SOT-563 footprint

### ISSUE THREAD

**Issue by Scalpel78** [KiCad/TO_SOT_Packages_SMD.pretty#9]
Could you add the SOT-563 footprint as well? 

See TMP102's datasheet for example: https://www.sparkfun.com/datasheets/Sensors/Temperature/tmp102.pdf

**Comment by CarlPoirier** [comment]
Hi @Scalpel78,

I invite you to draw the missing footprint and create a pull request to the appropriate repository. This way you will be able to contribute to KiCad.

Regards,

Carl
